/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class util_FUSELink */

#ifndef _Included_util_FUSELink
#define _Included_util_FUSELink
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     util_FUSELink
 * Method:    registerOperations
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_util_FUSELink_registerOperations
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
